[package]
name = "wavr"
version = "0.1.1"
authors = ["Richard Mitic <richard.h.mitic@gmail.com>"]
publish = false

[[bin]]
name = "wavr"
path = "src/main.rs"

[dependencies]
termion = "1.5.1"
hound = "3.3.1"
clap = "2.31.2"
itertools = "0.7.8"
rand = "0.3"
byteorder = "1.2.6"
rustfft = "3.0.0"
